<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'zCmsAdmin\Module'                                    => __DIR__ . '/Module.php',
  'zCmsAdmin\Controller\AssetsController'               => __DIR__ . '/src/zCmsAdmin/Controller/AssetsController.php',
  'zCmsAdmin\Controller\IndexController'                => __DIR__ . '/src/zCmsAdmin/Controller/IndexController.php',
  'zCmsAdmin\Navigation\Service\AdminNavigationFactory' => __DIR__ . '/src/zCmsAdmin/Navigation/Service/AdminNavigationFactory.php',
);
