<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <title>zCms <?php echo $this->translate('Admin'); ?></title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" />
        <link rel="stylesheet" href="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/css/fullcalendar.css" />
        <link rel="stylesheet" href="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/css/jquery.jscrollpane.css" />	
        <link rel="stylesheet" href="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/css/unicorn.css" />
        <link rel="stylesheet" href="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/css/unicorn.grey.css" class="skin-color" />
    </head>
    <body>
        <div id="header">
            <h1><a href="<?php echo $this->url('z-cms-admin'); ?>">zCmsAdmin</a></h1>	
            <a id="menu-trigger" href="#"><i class="icon-align-justify"></i></a>	
        </div>


        <div id="user-nav">
            <ul class="btn-group">
                <li class="btn" ><a title="" href="<?php echo $this->basePath('/user'); ?>"><i class="icon-user"></i> <span class="text"><?php echo $this->translate('Profile'); ?></span></a></li>
                <li class="btn"><a title="" href="<?php echo $this->basePath('/user'); ?>"><i class="icon-cog"></i> <span class="text"><?php echo $this->translate('Settings'); ?></span></a></li>
                <li class="btn"><a title="" href="<?php echo $this->basePath('/user/logout'); ?>"><i class="icon-share-alt"></i> <span class="text"><?php echo $this->translate('Log out'); ?></span></a></li>
            </ul>
        </div>

        <div id="sidebar">
            <?php echo $this->navigation('zadminnav_navigation')->menu()->setMaxDepth(4)->setPartial('zAdminSidenav'); ?>


        </div>
        <div id="content">
            <div id="content-header">
                <h1><?php echo $this->translate('Dashboard'); ?></h1>

            </div>
            <div id="breadcrumb">
                <?php echo $this->navigation('zadminnav_navigation')->breadcrumbs()->setPartial('zAdminBreadcrumbs'); ?>
            </div>
            <div class="container-fluid">

            </div>

        </div>
        <div class="row">
            <div id="footer" class="col-xs-12">
                2012 - <?php echo date("Y"); ?> &copy; zCms <?php echo $this->translate('Admin. Brought to you by'); ?> <a href="https://github.com/Nitecon">Nitecon</a>
            </div>
        </div>

        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/excanvas.min.js"></script>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/jquery.flot.min.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/jquery.flot.resize.min.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/jquery.sparkline.min.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/fullcalendar.min.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/jquery.jpanelmenu.min.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/jquery.nicescroll.min.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/unicorn.js"></script>
        <script src="http://nitecon-zcms.s3-website-us-east-1.amazonaws.com/js/unicorn.dashboard.js"></script>
    </body>
</html>
