<ul>
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li <?php if ($page->isActive()) echo 'class="active"' ?>>
                <a href="<?php echo $page->getHref() ?>"><i class="icon-th-list"></i>
                    <span><?php echo $this->translate($page->getLabel()) ?></span>
                </a>
            </li>
        <?php else: ?>
            <li <?php if ($page->isActive()){ echo 'class="active submenu open"'; }else{echo  'class="submenu"';} ?>>
                <a href="#"><i class="icon-th-list"></i><i class="arrow icon-chevron-right"></i>
                    <span><?php echo $this->translate($page->getLabel()) ?></span>
                </a>
                <ul>
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                    <li <?php if ($child->isActive()){ echo 'class="active"';} ?>>
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>   
        <?php endif ?>
        <?php $count++ ?>
    <?php endforeach ?>
</ul>